// Generated by CoffeeScript 1.7.1
var getRandomDanmu;

getRandomDanmu = function() {
  var count, i, randomArray, timer, _i;
  randomArray = new Array();
  for (i = _i = 0; _i < 7; i = ++_i) {
    randomArray[i] = i + 1;
  }
  randomArray.sort(function() {
    return 0.5 - Math.random();
  });
  count = 0;
  return timer = setInterval((function(_this) {
    return function() {
      count += 1;
      $(".danmu" + randomArray[count]).addClass("move");
      if (count === 6) {
        return clearInterval(timer);
      }
    };
  })(this), 1000);
};

$(function() {
  var $home, $load, $start;
  $load = $(".loading-page");
  $home = $(".home-page");
  $start = $('.start-pos');
  setTimeout((function(_this) {
    return function() {
      $load.hide();
      $home.show();
      return _this.getRandomDanmu();
    };
  })(this), 3500);
  return $start.on('click', function() {
    $home.hide();
    return console.log("game-start");
  });
});
