// Generated by CoffeeScript 1.7.1
(function() {
  var ajaxGet, debug, url;

  ajaxGet = function(url, _arg) {
    var fail, oReq, success;
    success = _arg.success, fail = _arg.fail;
    oReq = new XMLHttpRequest();
    oReq.onreadystatechange = function() {
      if (this.readyState !== 4) {
        return;
      }
      if (this.status === 200) {
        return typeof success === "function" ? success(this.responseText) : void 0;
      } else {
        return typeof fail === "function" ? fail("" + this.status + ": " + this.statusText) : void 0;
      }
    };
    oReq.open('get', url, true);
    return oReq.send();
  };

  debug = (location.search.match(/(?:\?|&)debug=(.*?)(?:&|$)/) || [void 0, ''])[1];

  url = debug === 'true' ? '/js-sdk-signature.json?debug=true' : '/js-sdk-signature.json';

  ajaxGet(url, {
    success: function(res) {
      var err;
      try {
        return wx.config(JSON.parse(res));
      } catch (_error) {
        err = _error;
      }
    }
  });

}).call(this);
